evotor/Evo-UI-Kit

- projects/evo-ui-kit/src/lib/modules/evo-paginator/evo-paginator.component.html
- projects/evo-ui-kit/src/lib/modules/evo-paginator/evo-paginator.component.scss
- projects/evo-ui-kit/src/lib/modules/evo-paginator/evo-paginator.component.spec.ts
- projects/evo-ui-kit/src/lib/modules/evo-paginator/evo-paginator.component.ts
- projects/evo-ui-kit/src/lib/modules/evo-paginator/evo-paginator.module.ts
- projects/evo-ui-kit/src/lib/modules/evo-paginator/public-api.ts
- projects/evo-ui-kit/src/public_api.ts
- src/stories/components/evo-paginator.stories.ts
New paginator component according visual kit. 
https://www.figma.com/file/TJMwN4a8wGEvVYTKQpUAbgC0/Evotor-UI-Kit?node-id=4623%3A0
> feat(paginator) introduce paginator component

- projects/evo-ui-kit/CHANGELOG.md
* **evo-datepicker:** corrected styles ([9dcd01d](https://github.com/evotor/Evo-UI-Kit/commit/9dcd01d))
* **evo-datepicker:** added maxRangeDays option ([44046b1](https://github.com/evotor/Evo-UI-Kit/commit/44046b1))
> chore(release): 2.10.0 [skip ci]

- projects/evo-ui-kit/CHANGELOG.md
- projects/evo-ui-kit/package.json
* **ci:** fixed tests task ([40b12c7](https://github.com/evotor/Evo-UI-Kit/commit/40b12c7))
* **evo-banner:** decrease full-width banner content width ([bfc7a88](https://github.com/evotor/Evo-UI-Kit/commit/bfc7a88))
* **evo-banner:** decrease full-width banner font size ([1e335ed](https://github.com/evotor/Evo-UI-Kit/commit/1e335ed))
* **evo-banner:** fix small banner styles ([4bd9191](https://github.com/evotor/Evo-UI-Kit/commit/4bd9191))
* **evo-banner:** fix styles, events ([824464e](https://github.com/evotor/Evo-UI-Kit/commit/824464e))
* **release:** fixed permissions problem in master ([ae891c2](https://github.com/evotor/Evo-UI-Kit/commit/ae891c2))
* **evo-banner:** listen window resize + adaptive based on host width ([de9694a](https://github.com/evotor/Evo-UI-Kit/commit/de9694a))
> chore(release): 2.11.0 [skip ci]

- projects/evo-ui-kit/src/lib/components/evo-select/evo-select.component.scss
- projects/evo-ui-kit/src/lib/components/evo-select/evo-select.component.ts
Добавил стили для валидного состояния (зеленый бордер при valid && touched)
> feat(select): +valid state styles

- projects/evo-ui-kit/src/lib/components/evo-select/evo-select.component.spec.ts
- projects/evo-ui-kit/src/lib/components/evo-select/evo-select.component.ts
Добавил обновление текста в `.evo-select__field` при изменении списка options.
Так как используется нативный options, QueryList не подходит, использовал MutationObserver.
> feat(select): upd on options changes

- projects/evo-ui-kit/src/lib/components/evo-upload/evo-upload.component.spec.ts
- projects/evo-ui-kit/src/lib/components/evo-upload/evo-upload.component.ts
Файлы с разрешением в верхнем регистре не проходили валидацию
> feat(upload): uppercase extension

- projects/evo-ui-kit/src/lib/components/evo-input/evo-input.component.spec.ts
- projects/evo-ui-kit/src/lib/components/evo-input/evo-input.component.ts
https://github.com/evotor/Evo-UI-Kit/issues/747
> fix(input): mask & prefix errors

- projects/evo-ui-kit/src/lib/components/evo-autocomplete/models/DaDataParty.ts
`feat(dadata): add some fields to model`
new fields:
```
okpo: string;
okved: string;
okato: string;
```
> Add some fields to DaDataParty model

- projects/evo-ui-kit/src/lib/components/evo-toast/evo-toast.component.spec.ts
- projects/evo-ui-kit/src/lib/components/evo-toast/evo-toast.component.ts
- src/stories/components/evo-toast-wrapper/evo-toast-wrapper.component.ts
Добавил поддержку `OnPush` стратегии.
> feat(evo-toast): add on push strategy support

- projects/evo-ui-kit/src/lib/components/evo-input/evo-input.component.scss
Fix prefix icon shrink when toggling clearable option
> fix(evo-input): prevent prefix icon shrink

- projects/evo-ui-kit/src/lib/components/evo-sidebar/evo-sidebar.component.ts
Добавил поддержку OnPush стратегии. Без этого приходится в компонентах дефолтную стратегию использовать, что не есть хорошо.
> feat(evo-sidebar): add onpush support

- projects/evo-ui-kit/src/lib/components/evo-popover/evo-popover.component.scss
EVOMRKT-4885 
https://jira.evotor.ru/browse/EVOMRKT-4885
> EVOMRKT-4885

- projects/evo-ui-kit/src/lib/components/evo-sidebar/evo-sidebar-header/evo-sidebar-header.component.scss
https://jira.evotor.ru/browse/EVOMRKT-4932
> EVOMRKT-4932

- projects/evo-ui-kit/src/lib/components/evo-input-contenteditable/evo-input-contenteditable.component.ts
- projects/evo-ui-kit/src/lib/components/evo-input-contenteditable/evo-input-contenteditable.spec.ts
- projects/evo-ui-kit/src/lib/components/evo-input-contenteditable/utils/clear-multiline.ts
- projects/evo-ui-kit/src/lib/utils/testing.ts
добавил тесты для компонента evo-input-contenteditable
[задача](https://jira.evotor.ru/browse/EVOMRKT-4953)
> feat(evo-input-contenteditable): added tests

- projects/evo-ui-kit/src/lib/styles/variables.scss
> [EVOMRKT-5018] Добавил новый цвет

- projects/evo-ui-kit/src/lib/components/evo-control-label/evo-control-label.component.scss
- projects/evo-ui-kit/src/lib/styles/components/evo-form.scss
https://jira.evotor.ru/browse/EVOMRKT-5066
> EVOMRKT-5066

- projects/evo-ui-kit/src/lib/styles/variables.scss
обновил тени (по просьбе Андрея Орешкина)
> feat(variables): added new shadows

- projects/evo-ui-kit/src/lib/components/evo-checkbox/evo-checkbox.component.scss
It makes control being available to select with tab navigation
> feat(evo-checkbox): tab navigation accessibility

- projects/evo-ui-kit/src/lib/components/evo-autocomplete/components/evo-autocomplete.component.scss
- projects/evo-ui-kit/src/lib/components/evo-input-contenteditable/evo-input-contenteditable.component.scss
- projects/evo-ui-kit/src/lib/components/evo-sidebar/evo-sidebar-footer/evo-sidebar-footer.component.scss
- projects/evo-ui-kit/src/lib/styles/mixins.scss
- projects/evo-ui-kit/src/lib/styles/variables.scss
- src/stories/components/evo-input-contenteditable.stories.ts
- src/stories/components/evo-input.stories.ts
https://jira.evotor.ru/browse/EVOMRKT-5133
> EVOMRKT-5133

- projects/evo-ui-kit/src/lib/components/evo-chip/evo-chip.component.html
- projects/evo-ui-kit/src/lib/components/evo-input/evo-input.component.html
- projects/evo-ui-kit/src/lib/components/evo-input/evo-input.component.scss
- src/stories/components/evo-input.stories.ts
- добавлен кастомный контент-префикса в input
- добавлен type=button для кнопки удалить в evo-chip
> feat(evo-input): add custom content inside input + type=button evo-chip

- projects/evo-ui-kit/src/lib/components/evo-alert/evo-alert.component.ts
- projects/evo-ui-kit/src/lib/components/evo-alert/evo-alert.module.ts
- projects/evo-ui-kit/src/lib/components/evo-note/evo-note.component.html
- projects/evo-ui-kit/src/lib/components/evo-note/evo-note.component.scss
- projects/evo-ui-kit/src/lib/components/evo-note/evo-note.component.spec.ts
- projects/evo-ui-kit/src/lib/components/evo-note/evo-note.component.ts
- projects/evo-ui-kit/src/lib/components/evo-note/evo-note.module.ts
- projects/evo-ui-kit/src/lib/components/evo-note/index.ts
- projects/evo-ui-kit/src/lib/components/evo-note/public.api.ts
- projects/evo-ui-kit/src/lib/components/evo-note/types/evo-note-type.ts
- projects/evo-ui-kit/src/lib/styles/variables.scss
- src/stories/components/evo-alert.stories.ts
- src/stories/components/evo-note.stories.ts
https://jira.evotor.ru/browse/EVOMRKT-5412
> EVOMRKT-5412

- projects/evo-ui-kit/src/lib/components/evo-paginator/evo-paginator.component.html
- projects/evo-ui-kit/src/lib/components/evo-paginator/evo-paginator.component.spec.ts
- projects/evo-ui-kit/src/lib/components/evo-paginator/evo-paginator.component.ts
- src/stories/components/evo-paginator.stories.ts
- page list calculation was wrong
> fix(evo-paginator): when near the end - last page hidden

- projects/evo-ui-kit/src/lib/components/evo-chip/evo-chip.component.html
- projects/evo-ui-kit/src/lib/components/evo-chip/evo-chip.component.spec.ts
Дать возможность отображать кнопку закрытия для любого типа чипс
> feat(evo-chip): add ability to show close chip button for any chip type

- projects/evo-ui-kit/src/lib/components/evo-upload/evo-upload.component.html
- projects/evo-ui-kit/src/lib/components/evo-upload/evo-upload.component.ts
Reverts evotor/Evo-UI-Kit#1119
> Revert "fix(evo-upload): remove checking mime in validators"

- projects/evo-ui-kit/src/lib/components/evo-sidebar/evo-sidebar-header/evo-sidebar-header.component.html
- projects/evo-ui-kit/src/lib/components/evo-sidebar/evo-sidebar-header/evo-sidebar-header.component.ts
- projects/evo-ui-kit/src/lib/components/evo-sidebar/evo-sidebar.component.html
- projects/evo-ui-kit/src/lib/components/evo-sidebar/evo-sidebar.component.spec.ts
- projects/evo-ui-kit/src/lib/components/evo-sidebar/evo-sidebar.component.ts
- projects/evo-ui-kit/src/lib/components/evo-sidebar/evo-sidebar.service.ts
- projects/evo-ui-kit/src/lib/components/evo-sidebar/interfaces.ts
Replace deprecated service to build dynamic components
Rework all getters and decorators into signals
Replace constructor DI with injects
Adjust tests
> feat(evo-sidebar): add params injector option

- projects/evo-ui-kit/src/lib/components/evo-input/evo-input.component.ts
fix(evo-input): satisfy abstract base control focus method
> Make evo-input satisfy BaseControl abstraction focus method

- projects/evo-ui-kit/CHANGELOG.md
- projects/evo-ui-kit/package.json
- projects/evo-ui-kit/src/lib/components/evo-badge/evo-badge.component.scss
- src/stories/components/evo-badge.stories.ts
- исправлена вёрстка вложенных в `evo-badge` иконок `evo-icon`
- обновлена документация `evo-badge`
> EVOMRKT-7574: исправления

- projects/evo-ui-kit/CHANGELOG.md
- projects/evo-ui-kit/package.json
- projects/evo-ui-kit/src/lib/components/evo-autocomplete/components/evo-autocomplete-default-option/evo-autocomplete-default-option.component.scss
- projects/evo-ui-kit/src/lib/components/evo-autocomplete/components/evo-autocomplete/evo-autocomplete.component.html
- projects/evo-ui-kit/src/lib/components/evo-autocomplete/components/evo-autocomplete/evo-autocomplete.component.scss
- src/stories/components/evo-autocomplete.stories.ts
Изменения:
1.  Обрезка кастомного мультилейбла автокомплита многоточием
2. Изменено дефолтное поведение опций автокомплита - включен перенос
3. Убрана заливка цветом выбранных опций в мультиселекте
> MRK-4443: Автокомплит: Пофиксить поведение лейбла мультиавтокомплита (v6)
